// Copyright (c) 2017-2023, University of Tennessee. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This program is free software: you can redistribute it and/or modify it under
// the terms of the BSD 3-Clause license. See the accompanying LICENSE file.

// Generated by tools/lapacke_suffix_gen.py; do not edit.
// Where lapack.h renamed LAPACK_x to LAPACK_x<suffix>, keeping LAPACK_x_base,
// maps LAPACK_x to the suffixed macro, so lapacke_wrappers.hh does not
// declare a conflicting prototype. Included after lapacke.h.

#if defined(LAPACK_chetrf_aa_base) && ! defined(LAPACK_chetrf_aa)
    #define LAPACK_chetrf_aa LAPACKE_NAME( LAPACK_chetrf_aa )
#endif
#if defined(LAPACK_clangb_base) && ! defined(LAPACK_clangb)
    #define LAPACK_clangb LAPACKE_NAME( LAPACK_clangb )
#endif
#if defined(LAPACK_clangt_base) && ! defined(LAPACK_clangt)
    #define LAPACK_clangt LAPACKE_NAME( LAPACK_clangt )
#endif
#if defined(LAPACK_clanhb_base) && ! defined(LAPACK_clanhb)
    #define LAPACK_clanhb LAPACKE_NAME( LAPACK_clanhb )
#endif
#if defined(LAPACK_clanhp_base) && ! defined(LAPACK_clanhp)
    #define LAPACK_clanhp LAPACKE_NAME( LAPACK_clanhp )
#endif
#if defined(LAPACK_clanhs_base) && ! defined(LAPACK_clanhs)
    #define LAPACK_clanhs LAPACKE_NAME( LAPACK_clanhs )
#endif
#if defined(LAPACK_clanht_base) && ! defined(LAPACK_clanht)
    #define LAPACK_clanht LAPACKE_NAME( LAPACK_clanht )
#endif
#if defined(LAPACK_clansb_base) && ! defined(LAPACK_clansb)
    #define LAPACK_clansb LAPACKE_NAME( LAPACK_clansb )
#endif
#if defined(LAPACK_clansp_base) && ! defined(LAPACK_clansp)
    #define LAPACK_clansp LAPACKE_NAME( LAPACK_clansp )
#endif
#if defined(LAPACK_clantb_base) && ! defined(LAPACK_clantb)
    #define LAPACK_clantb LAPACKE_NAME( LAPACK_clantb )
#endif
#if defined(LAPACK_clantp_base) && ! defined(LAPACK_clantp)
    #define LAPACK_clantp LAPACKE_NAME( LAPACK_clantp )
#endif
#if defined(LAPACK_clarf_base) && ! defined(LAPACK_clarf)
    #define LAPACK_clarf LAPACKE_NAME( LAPACK_clarf )
#endif
#if defined(LAPACK_clarfy_base) && ! defined(LAPACK_clarfy)
    #define LAPACK_clarfy LAPACKE_NAME( LAPACK_clarfy )
#endif
#if defined(LAPACK_csytrf_aa_base) && ! defined(LAPACK_csytrf_aa)
    #define LAPACK_csytrf_aa LAPACKE_NAME( LAPACK_csytrf_aa )
#endif
#if defined(LAPACK_ctplqt_base) && ! defined(LAPACK_ctplqt)
    #define LAPACK_ctplqt LAPACKE_NAME( LAPACK_ctplqt )
#endif
#if defined(LAPACK_ctplqt2_base) && ! defined(LAPACK_ctplqt2)
    #define LAPACK_ctplqt2 LAPACKE_NAME( LAPACK_ctplqt2 )
#endif
#if defined(LAPACK_ctpmlqt_base) && ! defined(LAPACK_ctpmlqt)
    #define LAPACK_ctpmlqt LAPACKE_NAME( LAPACK_ctpmlqt )
#endif
#if defined(LAPACK_dlaed4_base) && ! defined(LAPACK_dlaed4)
    #define LAPACK_dlaed4 LAPACKE_NAME( LAPACK_dlaed4 )
#endif
#if defined(LAPACK_dlangb_base) && ! defined(LAPACK_dlangb)
    #define LAPACK_dlangb LAPACKE_NAME( LAPACK_dlangb )
#endif
#if defined(LAPACK_dlangt_base) && ! defined(LAPACK_dlangt)
    #define LAPACK_dlangt LAPACKE_NAME( LAPACK_dlangt )
#endif
#if defined(LAPACK_dlanhs_base) && ! defined(LAPACK_dlanhs)
    #define LAPACK_dlanhs LAPACKE_NAME( LAPACK_dlanhs )
#endif
#if defined(LAPACK_dlansb_base) && ! defined(LAPACK_dlansb)
    #define LAPACK_dlansb LAPACKE_NAME( LAPACK_dlansb )
#endif
#if defined(LAPACK_dlansp_base) && ! defined(LAPACK_dlansp)
    #define LAPACK_dlansp LAPACKE_NAME( LAPACK_dlansp )
#endif
#if defined(LAPACK_dlanst_base) && ! defined(LAPACK_dlanst)
    #define LAPACK_dlanst LAPACKE_NAME( LAPACK_dlanst )
#endif
#if defined(LAPACK_dlantb_base) && ! defined(LAPACK_dlantb)
    #define LAPACK_dlantb LAPACKE_NAME( LAPACK_dlantb )
#endif
#if defined(LAPACK_dlantp_base) && ! defined(LAPACK_dlantp)
    #define LAPACK_dlantp LAPACKE_NAME( LAPACK_dlantp )
#endif
#if defined(LAPACK_dlarf_base) && ! defined(LAPACK_dlarf)
    #define LAPACK_dlarf LAPACKE_NAME( LAPACK_dlarf )
#endif
#if defined(LAPACK_dlarfy_base) && ! defined(LAPACK_dlarfy)
    #define LAPACK_dlarfy LAPACKE_NAME( LAPACK_dlarfy )
#endif
#if defined(LAPACK_dsytrf_aa_base) && ! defined(LAPACK_dsytrf_aa)
    #define LAPACK_dsytrf_aa LAPACKE_NAME( LAPACK_dsytrf_aa )
#endif
#if defined(LAPACK_dtplqt_base) && ! defined(LAPACK_dtplqt)
    #define LAPACK_dtplqt LAPACKE_NAME( LAPACK_dtplqt )
#endif
#if defined(LAPACK_dtplqt2_base) && ! defined(LAPACK_dtplqt2)
    #define LAPACK_dtplqt2 LAPACKE_NAME( LAPACK_dtplqt2 )
#endif
#if defined(LAPACK_dtpmlqt_base) && ! defined(LAPACK_dtpmlqt)
    #define LAPACK_dtpmlqt LAPACKE_NAME( LAPACK_dtpmlqt )
#endif
#if defined(LAPACK_slaed4_base) && ! defined(LAPACK_slaed4)
    #define LAPACK_slaed4 LAPACKE_NAME( LAPACK_slaed4 )
#endif
#if defined(LAPACK_slangb_base) && ! defined(LAPACK_slangb)
    #define LAPACK_slangb LAPACKE_NAME( LAPACK_slangb )
#endif
#if defined(LAPACK_slangt_base) && ! defined(LAPACK_slangt)
    #define LAPACK_slangt LAPACKE_NAME( LAPACK_slangt )
#endif
#if defined(LAPACK_slanhs_base) && ! defined(LAPACK_slanhs)
    #define LAPACK_slanhs LAPACKE_NAME( LAPACK_slanhs )
#endif
#if defined(LAPACK_slansb_base) && ! defined(LAPACK_slansb)
    #define LAPACK_slansb LAPACKE_NAME( LAPACK_slansb )
#endif
#if defined(LAPACK_slansp_base) && ! defined(LAPACK_slansp)
    #define LAPACK_slansp LAPACKE_NAME( LAPACK_slansp )
#endif
#if defined(LAPACK_slanst_base) && ! defined(LAPACK_slanst)
    #define LAPACK_slanst LAPACKE_NAME( LAPACK_slanst )
#endif
#if defined(LAPACK_slantb_base) && ! defined(LAPACK_slantb)
    #define LAPACK_slantb LAPACKE_NAME( LAPACK_slantb )
#endif
#if defined(LAPACK_slantp_base) && ! defined(LAPACK_slantp)
    #define LAPACK_slantp LAPACKE_NAME( LAPACK_slantp )
#endif
#if defined(LAPACK_slarf_base) && ! defined(LAPACK_slarf)
    #define LAPACK_slarf LAPACKE_NAME( LAPACK_slarf )
#endif
#if defined(LAPACK_slarfy_base) && ! defined(LAPACK_slarfy)
    #define LAPACK_slarfy LAPACKE_NAME( LAPACK_slarfy )
#endif
#if defined(LAPACK_ssytrf_aa_base) && ! defined(LAPACK_ssytrf_aa)
    #define LAPACK_ssytrf_aa LAPACKE_NAME( LAPACK_ssytrf_aa )
#endif
#if defined(LAPACK_stplqt_base) && ! defined(LAPACK_stplqt)
    #define LAPACK_stplqt LAPACKE_NAME( LAPACK_stplqt )
#endif
#if defined(LAPACK_stplqt2_base) && ! defined(LAPACK_stplqt2)
    #define LAPACK_stplqt2 LAPACKE_NAME( LAPACK_stplqt2 )
#endif
#if defined(LAPACK_stpmlqt_base) && ! defined(LAPACK_stpmlqt)
    #define LAPACK_stpmlqt LAPACKE_NAME( LAPACK_stpmlqt )
#endif
#if defined(LAPACK_zhetrf_aa_base) && ! defined(LAPACK_zhetrf_aa)
    #define LAPACK_zhetrf_aa LAPACKE_NAME( LAPACK_zhetrf_aa )
#endif
#if defined(LAPACK_zlangb_base) && ! defined(LAPACK_zlangb)
    #define LAPACK_zlangb LAPACKE_NAME( LAPACK_zlangb )
#endif
#if defined(LAPACK_zlangt_base) && ! defined(LAPACK_zlangt)
    #define LAPACK_zlangt LAPACKE_NAME( LAPACK_zlangt )
#endif
#if defined(LAPACK_zlanhb_base) && ! defined(LAPACK_zlanhb)
    #define LAPACK_zlanhb LAPACKE_NAME( LAPACK_zlanhb )
#endif
#if defined(LAPACK_zlanhp_base) && ! defined(LAPACK_zlanhp)
    #define LAPACK_zlanhp LAPACKE_NAME( LAPACK_zlanhp )
#endif
#if defined(LAPACK_zlanhs_base) && ! defined(LAPACK_zlanhs)
    #define LAPACK_zlanhs LAPACKE_NAME( LAPACK_zlanhs )
#endif
#if defined(LAPACK_zlanht_base) && ! defined(LAPACK_zlanht)
    #define LAPACK_zlanht LAPACKE_NAME( LAPACK_zlanht )
#endif
#if defined(LAPACK_zlansb_base) && ! defined(LAPACK_zlansb)
    #define LAPACK_zlansb LAPACKE_NAME( LAPACK_zlansb )
#endif
#if defined(LAPACK_zlansp_base) && ! defined(LAPACK_zlansp)
    #define LAPACK_zlansp LAPACKE_NAME( LAPACK_zlansp )
#endif
#if defined(LAPACK_zlantb_base) && ! defined(LAPACK_zlantb)
    #define LAPACK_zlantb LAPACKE_NAME( LAPACK_zlantb )
#endif
#if defined(LAPACK_zlantp_base) && ! defined(LAPACK_zlantp)
    #define LAPACK_zlantp LAPACKE_NAME( LAPACK_zlantp )
#endif
#if defined(LAPACK_zlarf_base) && ! defined(LAPACK_zlarf)
    #define LAPACK_zlarf LAPACKE_NAME( LAPACK_zlarf )
#endif
#if defined(LAPACK_zlarfy_base) && ! defined(LAPACK_zlarfy)
    #define LAPACK_zlarfy LAPACKE_NAME( LAPACK_zlarfy )
#endif
#if defined(LAPACK_zsytrf_aa_base) && ! defined(LAPACK_zsytrf_aa)
    #define LAPACK_zsytrf_aa LAPACKE_NAME( LAPACK_zsytrf_aa )
#endif
#if defined(LAPACK_ztplqt_base) && ! defined(LAPACK_ztplqt)
    #define LAPACK_ztplqt LAPACKE_NAME( LAPACK_ztplqt )
#endif
#if defined(LAPACK_ztplqt2_base) && ! defined(LAPACK_ztplqt2)
    #define LAPACK_ztplqt2 LAPACKE_NAME( LAPACK_ztplqt2 )
#endif
#if defined(LAPACK_ztpmlqt_base) && ! defined(LAPACK_ztpmlqt)
    #define LAPACK_ztpmlqt LAPACKE_NAME( LAPACK_ztpmlqt )
#endif
