#!/usr/bin/env python3

'''
lapacke_suffix_gen.py generates two headers that let the tester use a LAPACKE
whose symbols carry a suffix, as in OpenBLAS built with SYMBOLSUFFIX=64_.
test/lapacke_wrappers.hh includes them only when LAPACK_FORTRAN_SUFFIX or
BLAS_FORTRAN_SUFFIX is defined.

test/lapacke_suffix.hh, included before lapacke.h, maps each LAPACKE function
the tester calls to its suffixed name, e.g., LAPACKE_dgesv to LAPACKE_dgesv64_.
The functions are LAPACKE_* names found in test/*.cc and test/*.hh, ignoring
comments, string literals, and `#if 0` blocks, and omitting names the tester
defines itself (the generic overloads in lapacke_wrappers.hh, such as
LAPACKE_gesv).

test/lapack_suffix.hh, included after lapacke.h, handles the Fortran routines
that lapacke_wrappers.hh declares itself unless lapack.h defines LAPACK_x.
For routines with string arguments, OpenBLAS's suffixed lapack.h renames the
LAPACK_x macro to LAPACK_x64_ but keeps LAPACK_x_base, so the tester's
`#ifndef LAPACK_x` fallback would conflict with lapack.h's prototype.
When LAPACK_x_base is defined but LAPACK_x is not, this maps LAPACK_x to the
suffixed macro.

Rerun after adding LAPACKE calls or Fortran prototypes to the tester:

    lapackpp> ./tools/lapacke_suffix_gen.py
    generating test/lapacke_suffix.hh with 566 functions
    generating test/lapack_suffix.hh with 64 functions
'''

import glob
import os
import re

root = os.path.dirname( os.path.dirname( os.path.abspath( __file__ ) ) )
lapacke_file = os.path.join( 'test', 'lapacke_suffix.hh' )
lapack_file  = os.path.join( 'test', 'lapack_suffix.hh' )

header = '''\
// Copyright (c) 2017-2023, University of Tennessee. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This program is free software: you can redistribute it and/or modify it under
// the terms of the BSD 3-Clause license. See the accompanying LICENSE file.

// Generated by tools/lapacke_suffix_gen.py; do not edit.
'''

#-------------------------------------------------------------------------------
def strip_comments_strings( text ):
    '''
    Replaces comments and string and char literals with a space.
    '''
    regex = r'//[^\n]*|/\*.*?\*/|"(?:\\.|[^"\\\n])*"|\'(?:\\.|[^\'\\\n])*\''
    return re.sub( regex, ' ', text, flags=re.S )
# end

#-------------------------------------------------------------------------------
def strip_if0( text ):
    '''
    Removes `#if 0` blocks, keeping any `#else` branch. Handles nesting.
    '''
    out = []
    skip = 0    # nesting depth inside an `#if 0` block; 0 means not skipping
    for line in text.split( '\n' ):
        s = line.strip()
        if (skip):
            if (re.match( r'#\s*if', s )):
                skip += 1
            elif (re.match( r'#\s*endif', s )):
                skip -= 1
            elif (skip == 1 and re.match( r'#\s*(else|elif)', s )):
                skip = 0
            continue
        if (re.match( r'#\s*if\s+0\b', s )):
            skip = 1
            continue
        out.append( line )
    return '\n'.join( out )
# end

#-------------------------------------------------------------------------------
def write( filename, comment, lines, count ):
    print( 'generating', filename, 'with', count, 'functions' )
    with open( os.path.join( root, filename ), 'w' ) as f:
        f.write( header + comment + '\n' + ''.join( lines ) )
# end

#-------------------------------------------------------------------------------
def main():
    used    = set()  # LAPACKE_* names
    defined = set()  # LAPACKE_* names the tester defines
    fortran = set()  # LAPACK_* names the tester declares if lapack.h doesn't
    for filename in sorted( glob.glob( os.path.join( root, 'test', '*.cc' ) )
                          + glob.glob( os.path.join( root, 'test', '*.hh' ) ) ):
        if (filename.endswith( (lapacke_file, lapack_file) )):
            continue
        with open( filename ) as f:
            text = strip_if0( strip_comments_strings( f.read() ) )
        used.update( re.findall( r'\bLAPACKE_\w+', text ) )
        # Definitions start in column 0 with a return type, e.g.,
        # `inline lapack_int LAPACKE_gesv(`; calls are indented.
        defined.update( re.findall(
            r'^(?!return\b)[A-Za-z_][\w:<>,* ]*?[ *](LAPACKE_\w+)\s*\(',
            text, flags=re.M ) )
        # Macros the tester defines, e.g., LAPACKE_NAME.
        defined.update( re.findall( r'#\s*define\s+(LAPACKE_\w+)', text ) )
        # Fallback prototypes look like
        #     #ifndef LAPACK_slangb
        #     #define LAPACK_slangb LAPACK_GLOBAL(slangb,SLANGB)
        fortran.update( re.findall(
            r'^\s*#\s*ifndef\s+(LAPACK_\w+)\s*\n\s*#\s*define\s+\1\s+LAPACK_GLOBAL\b',
            text, flags=re.M ) )
    # end

    names = sorted( used - defined )
    width = max( map( len, names ) )
    write( lapacke_file,
           '// Maps each LAPACKE function the tester calls to its suffixed name.\n'
         + '// lapacke_wrappers.hh defines LAPACKE_NAME and includes this before lapacke.h.\n',
           [ '#define %-*s LAPACKE_NAME( %s )\n' % (width, name, name)
             for name in names ],
           len( names ) )

    names = sorted( fortran )
    write( lapack_file,
           '// Where lapack.h renamed LAPACK_x to LAPACK_x<suffix>, keeping LAPACK_x_base,\n'
         + '// maps LAPACK_x to the suffixed macro, so lapacke_wrappers.hh does not\n'
         + '// declare a conflicting prototype. Included after lapacke.h.\n',
           [ '#if defined(%s_base) && ! defined(%s)\n'
             '    #define %s LAPACKE_NAME( %s )\n'
             '#endif\n' % (name, name, name, name)
             for name in names ],
           len( names ) )
# end

#-------------------------------------------------------------------------------
if (__name__ == '__main__'):
    main()
